### ISSUE TITLE
Request: Multiple projects

### ISSUE THREAD

**Issue by georgecoca** [b-sharpe/SlackStorm#1]
Hi,

First, congrats for this plugin, it's really cool and useful. I would like to make a suggestion: It will be nice to have different configuration for different projects. Let's say you have in Phpstorm 2 projects, then I would like to configure it for different channels.

Thanks and keep up the good work! ;)

**Comment by b-sharpe** [comment]
Thanks. You read my mind, I was working on this yesterday. Should have a
working release posted soon :)

**Comment by b-sharpe** [comment]
Updated: https://plugins.jetbrains.com/plugin/8014?pr=idea_ce
