### ISSUE TITLE
Add Ability to edit a Slack channel configuration

### ISSUE THREAD

**Issue by rrajkomar** [b-sharpe/SlackStorm#10]
Hello,

I recently installed your plugin and it's really good. Congratz.
One thing bothers me a little though : you can't edit an already created channel. 
You can only delete it and then recreate it.

It would be nice if we could edit the channel settings even after it's been configured

**Comment by b-sharpe** [comment]
This is now an option. Updated in 51957afcb1130951bc4c1a3921c35d41423f3d6d and in new release in plugin repository: https://plugins.jetbrains.com/plugin/8014?pr=idea_ce

**Comment by rrajkomar** [comment]
This is now fixed.
Thanks a lot.
