### ISSUE TITLE
Message not sent, check your configuration

### ISSUE THREAD

**Issue by BorzdeG** [b-sharpe/SlackStorm#13]
0) created webhooks
1) added in IDEA channel settings
2) If you try to send something and IDEA, getting the message "Message not sent, check your configuration". However, no error messages in the logs of IDEA.

Environment: Linux, IDEA 2016.2 EAP (162.844.8)

**Comment by b-sharpe** [comment]
There currently is no logging when it fails, I probably should add that at some point.

Is there specific text that is failing? Or everything? Also, have you confirmed your webhook format xxx/yyy/zzzz in the settings and that the webhook works outside of the plugin?

Maybe something to do with EAP? I tested on latest Community Edition (15.0.6) and is working

**Comment by The-DL** [comment]
I just came across this due to having the same problem. Your post made me try it with out the 'https://hooks.slack.com/services/' portion of the webhook URL. 

Works fine now. 

I would suggest adding a check to see if it's the full URL or not, since the 'xxx/yyy/zzz/ isn't very clear.

**Comment by bric3** [comment]
Or at least handle with or without it, slack integration copies the whole URL, I had to check the documentation on the plugin page to find what was wrong.

**Comment by b-sharpe** [comment]
I've added into the latest release to support either format
