### ISSUE TITLE
Intelij Ultimate 2016.3 not see settings

### ISSUE THREAD

**Issue by krzpob** [b-sharpe/SlackStorm#15]
On Intelij Ultimate 2016.3 settings are not present in Tool section of preferences.
![zrzut ekranu 2016-12-04 o 03 03 04](https://cloud.githubusercontent.com/assets/88222/20863545/3dcee5ca-b9ce-11e6-9973-a09ecb40a849.png)

**Comment by b-sharpe** [comment]
The other tools at the top, between Run and VCS :)

**Comment by krzpob** [comment]
I find it
