### ISSUE TITLE
Can not find slack settings in Intellij IDEA

### ISSUE THREAD

**Issue by jjzhangg** [b-sharpe/SlackStorm#4]
Version: IntelliJ IDEA Community Edition 15.0.2

**Comment by jjzhangg** [comment]
or it's PHP IDEA only?

**Comment by b-sharpe** [comment]
It is for all versions, it just appears that org.apache.http doesn't exist in 15. When I have some time I'll see how to remedy this.

**Comment by anaelChardan** [comment]
I have the same problem in the latest version of PHPStorm and IntelliJ, have you find a solution ?

**Comment by b-sharpe** [comment]
I just uploaded the newest release:
https://plugins.jetbrains.com/plugin/8014?pr=

Source code also up to date
de9eee805eed5dfc6c822ef49a94fe3cb1a189bc

**Comment by jjzhangg** [comment]
@b-sharpe I have installed the latest version, but still, there's no slack settings. Anything to note?

**Comment by anaelChardan** [comment]
Hi, it works for me, thanks you, @jjzhangg have you see under the tools menu ? For me I had to simulate a share (by select a text and display the right click menu) after that, the menu under tools appeared.

**Comment by b-sharpe** [comment]
@jjzhangg try the latest build and let me know.

**Comment by jjzhangg** [comment]
Thanks Bryan, I see the settings now.
