### ISSUE TITLE
Can not post message include single quotation

### ISSUE THREAD

**Issue by watarukura** [b-sharpe/SlackStorm#5]
PHP Storm 10.0.2

Error message:
Error Occured.

**Comment by b-sharpe** [comment]
Can you provide an example? I have tested with both single and double and they are all working for me no problem.

**Comment by b-sharpe** [comment]
Nevermind, in my latest update I apparently forgot to URLencode :-1: 

Updated in latest release and commit 90e4a123b36a372556af0e5bcd631d4665b1dc22

**Comment by watarukura** [comment]
Thanks!:+1:
