### ISSUE TITLE
Web hook not working

### ISSUE THREAD

**Issue by IOIO72** [b-sharpe/SlackStorm#6]
I've pasted the web hook url into the SlackStorm settings without the url part (https://hooks.slack.com/services/). By sending a snipped SlackStorm responses with "an error occured".

I've also tried using the complete webhook url. SlackStorm confirms sending the message, but the message is never posted into the Slack channel.

**Comment by b-sharpe** [comment]
It is definitely without the URL part, just the token. Can you try reset all slack channels from the settings, and then try add again and make sure without the leading slash (xxx/yyy/zzz) and if it's still failing, can you post the following:
- IDEA Product (i.e. PHPStorm)
- IDEA Product version
- Plugin Version

**Comment by anaelChardan** [comment]
I had a problem too by trying to send a special message, it does not work with this specific message (I can't show you the message) but my config worked with other line, I think we should verify the message parsed. I will check that tonight.

**Comment by b-sharpe** [comment]
Closing. re-open if still an issue
