### ISSUE TITLE
Slack Settings don't appear in the Tools menu after install

### ISSUE THREAD

**Issue by BearOutThere** [b-sharpe/SlackStorm#8]
I installed SlackStorm on PHPStrom 10 on Ubuntu 14.04 but after restart no Slack related options are available on any menu so i can't configure the channel.  Tried reinstalling the plugin with the same result.  Any suggestions would be much appreciated.

**Comment by b-sharpe** [comment]
I just tested on 14.04 with PHPStorm 10.0.3 and can confirm it didn't show up on a couple occasions (sometimes it did). Restarting twice seems to fix it, and when that didn't work, I selected some text and right-clicked and then checked tools and it showed up... seems to work fine in fedora so not sure what's up here. Let me know if either of those solutions don't work for you

**Comment by BearOutThere** [comment]
Thanks for looking into it.  Tried all kinds of permutations together with re-downloading and re-installing.  just can't get it to show up.

**Comment by anaelChardan** [comment]
When I contributed to this project, I had the same problem, and indeed as b-sharpe said select some text and right click on it before try to open the Tools menu seems to work but it's not a real solution ^^

**Comment by BearOutThere** [comment]
Thanks for the suggestion.  I've been trying all sorts of things with reinstalling, selecting text, left clicking, right clicking.  Nothing Slack related shows up in the Tools menu.

**Comment by b-sharpe** [comment]
What version of Java? Are you installing the plugin from disk or from the in-app repo?

**Comment by BearOutThere** [comment]
Oracle JDK 7.  Plugin installed from disk.

It might have to do with the fact that i'm actually on PHP Storm  the
latest version of which is 10.  A friend installed your plugin on
Webstorm 11 and it works.

**Comment by b-sharpe** [comment]
I'm not sure what could be the problem. I've tested with multiple versions of the plugin and multiple versions of PHPStorm and they all work... Maybe try the install from web instead of from disk, other than that you may need to download the source and do some debug.
![capture](https://cloud.githubusercontent.com/assets/12438512/13735201/ea1fb55c-e963-11e5-9a64-eaeb019530fe.PNG)

**Comment by BearOutThere** [comment]
Tried installing from the repository and it's working.  Not sure what
the problem was with installing from disk.  Thanks for the support.

**Comment by b-sharpe** [comment]
Yay! closing :smile:
